[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
test = 'test'
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 200
remappings = [
    "@selfxyz/contracts/=node_modules/@selfxyz/contracts/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# RPC endpoints
[rpc_endpoints]
alfajores = "https://alfajores-forno.celo-testnet.org"
celo = "https://forno.celo.org"

# Etherscan API configuration
[etherscan]
alfajores = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
celo = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
single_line_statement_blocks = 'multi'

