[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
optimizer = true
solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 800
via_ir = false
ffi = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
single_line_statement_blocks = 'multi'

