[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
single_line_statement_blocks = 'multi'

